POST http://localhost:8080/cfsms/api/users
Content-Type: application/json

{"id":6,"login":"beijinguser1","firstName":" ","lastName":"北京","email":"BeijingUser1@localhost","imageUrl":null,"certDn":"1111","reviewStatus":"NORMAL","activated":true,"langKey":"zh-cn","createdBy":"zongbu","createdDate":"2020-03-19T10:16:09Z","lastModifiedBy":"security","lastModifiedDate":"2020-03-19T10:16:23Z","authorities":["ROLE_ADMIN_JU"],"department":{"id":4},"departmentId":4}

###


### 主页
http://localhost:8080/api/homepage?user=yichu
Authorization: Bearer {{auth_token}}
Accept: application/json
###

### 获取数据备份
GET http://localhost:8080/api/database-backups?page=0&size=10
Authorization: Bearer {{auth_token}}
Accept: application/json
###

### 获取日志
GET http://localhost:8080/cfsms/api/reports/users?login=beijinguser1
Cookie: KOAL_CERT_CN=11111
Authorization: Bearer {{auth_token}}
Accept: application/json
###

### 获取日志
GET http://localhost:8080/cfsms/api/log-backups?createdStartDate=2020-01-01&createdStartTime=23:03:21&createdEndDate=2020-04-01&createdEndTime=23:03:21&level=INFO&page=0&size=10
Authorization: Bearer {{auth_token}}
Accept: application/json
###

### 修改密码
POST http://localhost:8080/api/account/change-password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "password":"security",
    "oldPassword": "user"
}
###
### 用户认证
POST http://localhost:8080/cfsms/api/authenticate
Content-Type: application/json

{
    "username": "BeijingUser1@localhost",
    "password": "BeijingUser1"
}

> {% client.global.set("auth_token", response.body.id_token); %}

### 用户认证-证书
POST http://localhost:8080/cfsms/api/authenticate/cert
Content-Type: application/json
Cookie: KOAL_CERT_CN=11112
Cookie:

> {% client.global.set("auth_token", response.body.id_token); %}

### 导出报告
GET http://localhost:8080/api/exportReport?reportId=1
Authorization: Bearer {{auth_token}}

<> /Users/kebei/Desktop/自查自纠/自查自评结果2.doc
### 导入报告
POST http://localhost:8080/api/importReport
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="自查自评结果.doc"

< /Users/kebei/Desktop/1584326179000.doc
--WebAppBoundary--

###
